// <auto-generated />
namespace Peer2peer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DonationPackage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DonationPackage));
        
        string IMigrationMetadata.Id
        {
            get { return "201703190615569_DonationPackage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
